# recipes/recipe.yml
name: flow-os
description: FlowOS 1.0 Salix 
base-image: ghcr.io/ublue-os/silverblue-main:41

settings:
  os-name: "FlowOS"
  version: "1.0 Salix"

modules:
  # 1. HARDWARE (Surface Go Support)
  - type: rpm-ostree
    repos:
      - https://pkg.surfacelinux.com/fedora/linux-surface.repo
    install:
      - kernel-surface
      - iptsd
      - surface-control
      - libwacom-surface
      - plymouth-theme-spinner
      - gnome-initial-setup
      - inter-fonts

  # 2. DESIGN & TOOLS
  - type: rpm-ostree
    install:
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-tiling-shell
      - gnome-shell-extension-gesture-improvements
      - gnome-clocks
      - gnome-calculator
      - gnome-camera
      - gnome-online-accounts
      - adw-gtk3-theme

  # 3. APPS (Flatpaks)
  - type: flatpak
    first-run: true
    install:
      - org.mozilla.firefox
      - com.github.rahuljennings.rnote
      - org.gnome.Geary
      - com.github.johnfactotum.Foliate
      - org.gnome.Loupe
      - io.github.bavarder.Bavarder

  # 4. REINHEITS-GEBOT & AUTO-GESTURE
  - type: script
    snippets:
      - "echo 'NoDisplay=true' >> /usr/share/applications/org.gnome.Terminal.desktop"
      - "gsettings set org.gnome.shell enabled-extensions \"['dash-to-dock@micxgx.gmail.com', 'blur-my-shell@aunetx', 'tiling-shell@sbdub.github.com', 'gesture-improvements@jasonu.me']\""

  # 5. UX-FINISH
  - type: default-settings
    dconf:
      org/gnome/desktop/interface/font-name: 'Inter Regular 11'
      org/gnome/desktop/interface/text-scaling-factor: 1.5
      org/gnome/desktop/interface/color-scheme: 'prefer-dark'
      org/gnome/shell/extensions/dash-to-dock/dock-fixed: false
      org/gnome/shell/extensions/dash-to-dock/autohide: true
      org/gnome/shell/extensions/dash-to-dock/dock-position: 'LEFT'
      org/gnome/desktop/wm/preferences/button-layout: "''"
